# Generated by Django 3.2.16 on 2022-12-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='fefde', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
